#port => default 8080
#spring => 데이터베이스 (datasource)
server: 
    servlet:
        context-path: /
spring:
    # 파일업로드
    servlet:
        multipart:
            enabled: true
            max-file-size: 100MB
            max-request-size: 100MB
    datasource:
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: oracle.jdbc.driver.OracleDriver

    #데이터베이스를 객체화시켜주는게 hibernate => jpa
    #properties : hibernate / mybatis
    # 각 데이터베이스의 맞는 sql문장을 생성한다 =>  dialect: org.hibernate.dialect.OracleDialect
    # JPA => Hibernate => SQL문장 생성 => oracle db 실행
    # web => upload
    jpa:
        database: oracle
        properties:
            hibernate:
                dialect: org.hibernate.dialect.OracleDialect
                format-sql: true
                user-sql-comments: true
    thymeleaf:
        cache: false
        encoding: UTF-8
        prefix: classpath:/templates/
        suffix: .html
        mode: HTML
file:
    upload_dir: C:/upload
mybatis:
    type-aliases-package: com.sist.web.vo
    mapper-locations: mybatis/mapper/*.xml
logging:
    level:
        org.hibernate.SQL: debug
        org.hibernate.orm.jdbc.bind: trace
